deployment:
  tasks:
    - cd /home/lucaswalsh/repositories/Portfolio-Website
    - /bin/npm install
    - /bin/npm run build
    - export DEPLOYPATH=/home/lucaswalsh/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH
